CREATE TABLE ManyToOneOwner (Id INTEGER NOT NULL PRIMARY KEY, Name VARCHAR, Height INTEGER, Weight INTEGER, Email VARCHAR, HireFiscalYear INTEGER, Birthday DATE, BloodType VARCHAR, Version INTEGER DEFAULT 1, OneToManyInverse_Id INTEGER NOT NULL)
CREATE TABLE OneToManyInverse (Id INTEGER NOT NULL PRIMARY KEY, Name VARCHAR, Version INTEGER DEFAULT 1)

CREATE SEQUENCE ManyToOneOwner_Id_Sequence START WITH 100
CREATE SEQUENCE OneToManyInverse_Id_Sequence START WITH 100

CREATE TABLE dual_ManyToOneOwner_Id_Sequence (zero INTEGER)
CREATE TABLE dual_OneToManyInverse_Id_Sequence (zero INTEGER)

CREATE USER SA PASSWORD "" ADMIN
SET WRITE_DELAY 60

-- <Sequences>
INSERT INTO dual_ManyToOneOwner_Id_Sequence VALUES (0)
INSERT INTO dual_OneToManyInverse_Id_Sequence VALUES (0)

-- <ManyToOneOwners>
INSERT INTO ManyToOneOwner VALUES (1,'シマゴロー',168,72,'simagoro@nekoyasudo',1984,'1953-10-01','A', 1, 1)
INSERT INTO ManyToOneOwner VALUES (2,'ゴッチン',161,60,'gochin@nekoyasudo',1984,'1950-12-25','B', 1, 1)
INSERT INTO ManyToOneOwner VALUES (3,'マキ子',155,52,'maki@nekoyasudo',1984,'1955-08-16','O', 1, 1)
INSERT INTO ManyToOneOwner VALUES (4,'マル',158,45,'maru@nekoyasudo',1984,'1951-01-12','AB', 1 , 1)
INSERT INTO ManyToOneOwner VALUES (5,'ミチロー',170,70,'michiro@nekoyasudo',1984,'1962-02-14','A', 1, 1)
INSERT INTO ManyToOneOwner VALUES (6,'クー',173,76,'coo@nekoyasudo',1984,'1961-09-15','A', 1, 1)
INSERT INTO ManyToOneOwner VALUES (7,'サラ',162,50,'sara@nekoyasudo',1985,'1957-10-28','A', 1, 1)
INSERT INTO ManyToOneOwner VALUES (8,'みなみ',153,42,'minami@nekoyasudo',1985,'1959-09-03','O', 1, 1)
INSERT INTO ManyToOneOwner VALUES (9,'プリン',148,48,'prin@nekoyasudo',1985,'1965-03-14','B', 1, 1)
INSERT INTO ManyToOneOwner VALUES (10,'ぴー子',156,52,'pko@nekoyasudo',1985,'1968-11-13','O', 1, 1)
INSERT INTO ManyToOneOwner VALUES (11,'ごま',180,78,'goma@nekoyasudo',1985,'1968-04-15','O', 1, 2)
INSERT INTO ManyToOneOwner VALUES (12,'ぱんだ',185,95,'panda@nekoyasudo',1985,'1968-06-01','B', 1, 2)
INSERT INTO ManyToOneOwner VALUES (13,'猫丸',172,80,'nekomaru@nekoyasudo',1986,'1969-01-15','B', 1, 3)
INSERT INTO ManyToOneOwner VALUES (14,'にゃん太郎',178,58,'nyantaro@nekoyasudo',1986,'1969-02-03','B', 1, 3)
INSERT INTO ManyToOneOwner VALUES (15,'モンチー',169,55,'monchi@nekoyasudo',1988,'1970-05-06','A', 1, 3)
INSERT INTO ManyToOneOwner VALUES (16,'ぴよ',155,62,'piyo@nekoyasudo',1988,'1970-07-14','A', 1, 4)
INSERT INTO ManyToOneOwner VALUES (17,'ラスカル',165,51,'rasukal@nekoyasudo',1989,'1971-04-10','AB', 1, 4)
INSERT INTO ManyToOneOwner VALUES (18,'くま',190,115,'kuma@nekoyasudo',1989,'1967-03-03','O', 1, 4)
INSERT INTO ManyToOneOwner VALUES (19,'ゴン',176,78,'gon@nekoyasudo',1990,'1972-11-16','O', 1, 4)
INSERT INTO ManyToOneOwner VALUES (20,'キュー',169,56,'q@nekoyasudo',1991,'1973-05-25','O', 1, 5)
INSERT INTO ManyToOneOwner VALUES (21,'太助',164,50,'tasuke@nekoyasudo',1993,'1975-10-03','B', 1, 5)
INSERT INTO ManyToOneOwner VALUES (22,'トントン',155,45,'tonton@nekoyasudo',1993,'1975-12-25','B', 1, 5)
INSERT INTO ManyToOneOwner VALUES (23,'マー',158,44,'ma@nekoyasudo',1994,'1976-04-03','A', 1, 5)
INSERT INTO ManyToOneOwner VALUES (24,'サリー',149,38,'sary@nekoyasudo',1996,'1978-02-02','A', 1, 5)
INSERT INTO ManyToOneOwner VALUES (25,'うさぎ',161,43,'usa@nekoyasudo',1996,'1978-08-08','A', 1, 6)
INSERT INTO ManyToOneOwner VALUES (26,'うー太',170,63,'uta@nekoyasudo',1998,'1980-03-26','A', 1, 6)
INSERT INTO ManyToOneOwner VALUES (27,'ローリー',147,40,'roly@nekoyasudo',2000,'1982-05-26','A', 1, 6)
INSERT INTO ManyToOneOwner VALUES (28,'マイケル',160,49,'mikel@nekoyasudo',2001,'1983-06-30','AB', 1, 6)
INSERT INTO ManyToOneOwner VALUES (29,'スー',163,52,'su@nekoyasudo',2003,'1985-09-08','O', 1, 6)
INSERT INTO ManyToOneOwner VALUES (30,'ミーヤ',168,51,'miya@nekoyasudo',2004,'1986-07-07','B', 1, 6)

-- <OneToManyInverses>
INSERT INTO OneToManyInverse VALUES (1,'営業', 1, 1)
INSERT INTO OneToManyInverse VALUES (2,'総務', 1, 1)
INSERT INTO OneToManyInverse VALUES (3,'人事', 1, 1)
INSERT INTO OneToManyInverse VALUES (4,'経理', 1, 1)
INSERT INTO OneToManyInverse VALUES (5,'販売', 1, 1)
INSERT INTO OneToManyInverse VALUES (6,'購買', 1, 1)
