CREATE TABLE OneToManyInverse (Id INTEGER NOT NULL PRIMARY KEY, Name VARCHAR, Version INTEGER DEFAULT 1)
CREATE TABLE ManyToOneOwner (Id INTEGER NOT NULL PRIMARY KEY, Name VARCHAR, Height INTEGER, Weight INTEGER, Email VARCHAR, HireFiscalYear INTEGER, Birthday DATE, BloodType VARCHAR, EmployeeStatus INTEGER, SalaryRate VARCHAR, Version INTEGER DEFAULT 1, OneToManyInverse_Id INTEGER NOT NULL, FOREIGN KEY (OneToManyInverse_Id) REFERENCES OneToManyInverse (Id))
CREATE TABLE OneToOneInverse (Id INTEGER NOT NULL PRIMARY KEY, Name VARCHAR, Version INTEGER DEFAULT 1)
CREATE TABLE OneToOneOwner (Id INTEGER NOT NULL PRIMARY KEY, Name VARCHAR, Height INTEGER, Weight INTEGER, Email VARCHAR, HireFiscalYear INTEGER, Birthday DATE, BloodType VARCHAR, EmployeeStatus INTEGER, SalaryRate VARCHAR, Version INTEGER DEFAULT 1, OneToOneInverse_Id INTEGER NOT NULL, UNIQUE (OneToOneInverse_Id), FOREIGN KEY (OneToOneInverse_Id) REFERENCES OneToOneInverse (Id))
CREATE TABLE ManyToManyInverse (Id INTEGER NOT NULL PRIMARY KEY, Name VARCHAR, Version INTEGER DEFAULT 1)
CREATE TABLE ManyToManyOwner (Id INTEGER NOT NULL PRIMARY KEY, Name VARCHAR, Height INTEGER, Weight INTEGER, Email VARCHAR, HireFiscalYear INTEGER, Birthday DATE, BloodType VARCHAR, EmployeeStatus INTEGER, SalaryRate VARCHAR, Version INTEGER DEFAULT 1)
CREATE TABLE ManyToManyOwner_ManyToManyInverse (ManyToManyOwners_Id INTEGER NOT NULL,ManyToManyInverses_Id INTEGER NOT NULL, PRIMARY KEY (ManyToManyOwners_Id, ManyToManyInverses_Id), FOREIGN KEY (ManyToManyOwners_Id) REFERENCES ManyToManyOwner (Id), FOREIGN KEY (ManyToManyInverses_Id) REFERENCES ManyToManyInverse (Id))

CREATE SEQUENCE OneToManyInverse_Id_Sequence START WITH 100
CREATE SEQUENCE ManyToOneOwner_Id_Sequence START WITH 100
CREATE SEQUENCE OneToOneInverse_Id_Sequence START WITH 100
CREATE SEQUENCE OneToOneOwner_Id_Sequence START WITH 100
CREATE SEQUENCE ManyToManyInverse_Id_Sequence START WITH 100
CREATE SEQUENCE ManyToManyOwner_Id_Sequence START WITH 100

CREATE TABLE dual_OneToManyInverse_Id_Sequence (zero INTEGER)
CREATE TABLE dual_ManyToOneOwner_Id_Sequence (zero INTEGER)
CREATE TABLE dual_OneToOneInverse_Id_Sequence (zero INTEGER)
CREATE TABLE dual_OneToOneOwner_Id_Sequence (zero INTEGER)
CREATE TABLE dual_ManyToManyInverse_Id_Sequence (zero INTEGER)
CREATE TABLE dual_ManyToManyOwner_Id_Sequence (zero INTEGER)

CREATE USER SA PASSWORD "" ADMIN
SET WRITE_DELAY 60

-- <Sequences>
INSERT INTO dual_OneToManyInverse_Id_Sequence VALUES (0)
INSERT INTO dual_ManyToOneOwner_Id_Sequence VALUES (0)
INSERT INTO dual_OneToOneInverse_Id_Sequence VALUES (0)
INSERT INTO dual_OneToOneOwner_Id_Sequence VALUES (0)
INSERT INTO dual_ManyToManyInverse_Id_Sequence VALUES (0)
INSERT INTO dual_ManyToManyOwner_Id_Sequence VALUES (0)

-- <OneToManyInverses>
INSERT INTO OneToManyInverse VALUES (1,'Business', 1)
INSERT INTO OneToManyInverse VALUES (2,'General Administration', 1)
INSERT INTO OneToManyInverse VALUES (3,'Personnel', 1)
INSERT INTO OneToManyInverse VALUES (4,'Account', 1)
INSERT INTO OneToManyInverse VALUES (5,'Sales', 1)
INSERT INTO OneToManyInverse VALUES (6,'Purchase', 1)

-- <ManyToOneOwners>
INSERT INTO ManyToOneOwner VALUES (1,'simagoro',168,72,'simagoro@nekoyasudo',NULL,'1953-10-01','A', 0, 'JUNIOR', 1, 1)
INSERT INTO ManyToOneOwner VALUES (2,'gochin',161,60,'gochin@nekoyasudo',1984,'1950-12-25','B', 1, 'JUNIOR', 1, 1)
INSERT INTO ManyToOneOwner VALUES (3,'maki',155,52,'maki@nekoyasudo',1984,'1955-08-16','O', 2, 'MANAGER', 1, 1)
INSERT INTO ManyToOneOwner VALUES (4,'maru',158,45,'maru@nekoyasudo',1984,'1951-01-12','AB', 0, 'JUNIOR', 1 , 1)
INSERT INTO ManyToOneOwner VALUES (5,'michiro',170,70,'michiro@nekoyasudo',1984,'1962-02-14','A', 1, 'SENIOR', 1, 1)
INSERT INTO ManyToOneOwner VALUES (6,'coo',173,76,'coo@nekoyasudo',1984,'1961-09-15','A', 2, 'JUNIOR', 1, 1)
INSERT INTO ManyToOneOwner VALUES (7,'sara',162,50,'sara@nekoyasudo',1985,'1957-10-28','A', 0, 'JUNIOR', 1, 1)
INSERT INTO ManyToOneOwner VALUES (8,'minami',153,42,'minami@nekoyasudo',1985,'1959-09-03','O', 1, 'JUNIOR', 1, 1)
INSERT INTO ManyToOneOwner VALUES (9,'prin',148,48,'prin@nekoyasudo',1985,'1965-03-14','B', 2, 'JUNIOR', 1, 1)
INSERT INTO ManyToOneOwner VALUES (10,'pko',156,52,'pko@nekoyasudo',1985,'1968-11-13','O', 0, 'SENIOR', 1, 1)
INSERT INTO ManyToOneOwner VALUES (11,'goma',180,78,'goma@nekoyasudo',1985,'1968-04-15','O', 1, 'JUNIOR', 1, 2)
INSERT INTO ManyToOneOwner VALUES (12,'panda',185,95,'panda@nekoyasudo',1985,'1968-06-01','B', 2, 'JUNIOR', 1, 2)
INSERT INTO ManyToOneOwner VALUES (13,'nekomaru',172,80,'nekomaru@nekoyasudo',1986,'1969-01-15','B', 0, 'MANAGER', 1, 3)
INSERT INTO ManyToOneOwner VALUES (14,'nyantaro',178,58,'nyantaro@nekoyasudo',1986,'1969-02-03','B', 1, 'JUNIOR', 1, 3)
INSERT INTO ManyToOneOwner VALUES (15,'monchi',169,55,'monchi@nekoyasudo',1988,'1970-05-06','A', 2, 'SENIOR', 1, 3)
INSERT INTO ManyToOneOwner VALUES (16,'piyo',155,62,'piyo@nekoyasudo',1988,'1970-07-14','A', 0, 'JUNIOR', 1, 4)
INSERT INTO ManyToOneOwner VALUES (17,'rasukal',165,51,'rasukal@nekoyasudo',1989,'1971-04-10','AB', 1, 'JUNIOR', 1, 4)
INSERT INTO ManyToOneOwner VALUES (18,'kuma',190,115,'kuma@nekoyasudo',1989,'1967-03-03','O', 2, 'JUNIOR', 1, 4)
INSERT INTO ManyToOneOwner VALUES (19,'gon',176,78,'gon@nekoyasudo',1990,'1972-11-16','O', 0, 'JUNIOR', 1, 4)
INSERT INTO ManyToOneOwner VALUES (20,'q',169,56,'q@nekoyasudo',1991,'1973-05-25','O', 1, 'SENIOR', 1, 5)
INSERT INTO ManyToOneOwner VALUES (21,'tasuke',164,50,'tasuke@nekoyasudo',1993,'1975-10-03','B', 2, 'JUNIOR', 1, 5)
INSERT INTO ManyToOneOwner VALUES (22,'tonton',155,45,'tonton@nekoyasudo',1993,'1975-12-25','B', 0, 'JUNIOR', 1, 5)
INSERT INTO ManyToOneOwner VALUES (23,'ma',158,44,'ma@nekoyasudo',1994,'1976-04-03','A', 1, 'MANAGER', 1, 5)
INSERT INTO ManyToOneOwner VALUES (24,'sary',149,38,'sary@nekoyasudo',1996,'1978-02-02','A', 2, 'JUNIOR', 1, 5)
INSERT INTO ManyToOneOwner VALUES (25,'usa',161,43,'usa@nekoyasudo',1996,'1978-08-08','A', 0, 'SENIOR', 1, 6)
INSERT INTO ManyToOneOwner VALUES (26,'uta',170,63,'uta@nekoyasudo',1998,'1980-03-26','A', 1, 'JUNIOR', 1, 6)
INSERT INTO ManyToOneOwner VALUES (27,'roly',147,40,'roly@nekoyasudo',2000,'1982-05-26','A', 2, 'JUNIOR', 1, 6)
INSERT INTO ManyToOneOwner VALUES (28,'mikel',160,49,'mikel@nekoyasudo',2001,'1983-06-30','AB', 0, 'JUNIOR', 1, 6)
INSERT INTO ManyToOneOwner VALUES (29,'su',163,52,'su@nekoyasudo',2003,'1985-09-08','O', 1, 'JUNIOR', 1, 6)
INSERT INTO ManyToOneOwner VALUES (30,'miya',168,51,'miya@nekoyasudo',2004,'1986-07-07','B', 2, 'SENIOR', 1, 6)

-- <OneToOneInverses>
INSERT INTO OneToOneInverse VALUES (1,'Business', 1)
INSERT INTO OneToOneInverse VALUES (2,'General Administration', 1)
INSERT INTO OneToOneInverse VALUES (3,'Personnel', 1)
INSERT INTO OneToOneInverse VALUES (4,'Account', 1)
INSERT INTO OneToOneInverse VALUES (5,'Sales', 1)
INSERT INTO OneToOneInverse VALUES (6,'Purchase', 1)

-- <OneToOneOwners>
INSERT INTO OneToOneOwner VALUES (1,'simagoro',168,72,'simagoro@nekoyasudo',NULL,'1953-10-01','A', 0, 'JUNIOR', 1, 1)
INSERT INTO OneToOneOwner VALUES (2,'gochin',161,60,'gochin@nekoyasudo',1984,'1950-12-25','B', 1, 'JUNIOR', 1, 2)
INSERT INTO OneToOneOwner VALUES (3,'maki',155,52,'maki@nekoyasudo',1984,'1955-08-16','O', 2, 'MANAGER', 1, 3)
INSERT INTO OneToOneOwner VALUES (4,'maru',158,45,'maru@nekoyasudo',1984,'1951-01-12','AB', 0, 'JUNIOR', 1 , 4)
INSERT INTO OneToOneOwner VALUES (5,'michiro',170,70,'michiro@nekoyasudo',1984,'1962-02-14','A', 1, 'SENIOR', 1, 5)
INSERT INTO OneToOneOwner VALUES (6,'coo',173,76,'coo@nekoyasudo',1984,'1961-09-15','A', 2, 'JUNIOR', 1, 6)

-- <ManyToManyInverses>
INSERT INTO ManyToManyInverse VALUES (1,'Business', 1)
INSERT INTO ManyToManyInverse VALUES (2,'General Administration', 1)
INSERT INTO ManyToManyInverse VALUES (3,'Personnel', 1)
INSERT INTO ManyToManyInverse VALUES (4,'Account', 1)
INSERT INTO ManyToManyInverse VALUES (5,'Sales', 1)
INSERT INTO ManyToManyInverse VALUES (6,'Purchase', 1)

-- <ManyToManyOwners>
INSERT INTO ManyToManyOwner VALUES (1,'simagoro',168,72,'simagoro@nekoyasudo',NULL,'1953-10-01','A', 0, 'JUNIOR', 1)
INSERT INTO ManyToManyOwner VALUES (2,'gochin',161,60,'gochin@nekoyasudo',1984,'1950-12-25','B', 1, 'JUNIOR', 1)
INSERT INTO ManyToManyOwner VALUES (3,'maki',155,52,'maki@nekoyasudo',1984,'1955-08-16','O', 2, 'MANAGER', 1)
INSERT INTO ManyToManyOwner VALUES (4,'maru',158,45,'maru@nekoyasudo',1984,'1951-01-12','AB', 0, 'JUNIOR', 1)
INSERT INTO ManyToManyOwner VALUES (5,'michiro',170,70,'michiro@nekoyasudo',1984,'1962-02-14','A', 1, 'SENIOR', 1)
INSERT INTO ManyToManyOwner VALUES (6,'coo',173,76,'coo@nekoyasudo',1984,'1961-09-15','A', 2, 'JUNIOR', 1)

-- <ManyToManyOwner_ManyToManyInverse>
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (1, 1)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (2, 1)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (2, 2)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (3, 1)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (3, 2)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (3, 3)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (4, 1)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (4, 2)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (4, 3)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (4, 4)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (5, 1)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (5, 2)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (5, 3)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (5, 4)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (5, 5)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (6, 1)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (6, 2)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (6, 3)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (6, 4)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (6, 5)
INSERT INTO ManyToManyOwner_ManyToManyInverse VALUES (6, 6)
